version: '3.7'
services:
  currency-exchange:
    # docker run -p 8000:8000 -d --name=currency-exchange
    # --network=currency-network in28min/currency-exchange:0.0.1-RELEASE
    build: ./01-currency-exchange-microservice-basic
    # image: in28min/currency-exchange:0.0.1-RELEASE
    ports:
      - "8000:8000"
    restart: always
    networks:
      - currency-compose-network

  currency-conversion:
    # docker run -p 8100:8100 -d --name=currency-conversion
    # --env=CURRENCY_EXCHANGE_SERVICE_HOST=http://currency-exchange
    # --network=currency-network in28min/currency-conversion:0.0.1-RELEASE
    build: ./02-currency-conversion-microservice-basic
    # image: in28min/currency-conversion:0.0.1-RELEASE
    ports:
      - "8100:8100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_SERVICE_HOST: http://currency-exchange
    depends_on:
      - currency-exchange
    networks:
      - currency-compose-network

# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network: