# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
# triggered on master branch
- master

pool: SelfPool

# Pipelines -> Stages (qa, prod) -> Jobs -> Tasks (Steps)

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
- stage: DevDeploy
  # add stage dependency
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo Build DevDeployJob
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo Build QADeployJob
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Build ProdDeployJob
