apiVersion: apps/v1
kind: Deployment  # type, could be Deployment, Service, ReplicaSet
# info about deployment
metadata:
  labels:
    app: hello-world-rest-api
    version: v1
  name: hello-world-rest-api-v1
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45  # give the container 45sec and only then send the request
  selector:  # how pod is mapped to a deployment
    matchLabels:
      app: hello-world-rest-api
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%  # how many instances to create each time
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api  # label of a pod
        version: v1
    spec:
      containers:
      - image: in28min/hello-world-rest-api:0.0.1.RELEASE  # docker image, could be many images
        imagePullPolicy: IfNotPresent  # pull image if not present, could be also Always
        name: hello-world-rest-api  # container name
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment  # type, could be Deployment, Service, ReplicaSet
# info about deployment
metadata:
  labels:
    app: hello-world-rest-api
    version: v1
  name: hello-world-rest-api-v2
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45  # give the container 45sec and only then send the request
  selector:  # how pod is mapped to a deployment
    matchLabels:
      app: hello-world-rest-api
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 25%  # how many instances to create each time
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api  # label of a pod
        version: v2
    spec:
      containers:
      - image: in28min/hello-world-rest-api:0.0.2.RELEASE  # docker image, could be many images
        imagePullPolicy: IfNotPresent  # pull image if not present, could be also Always
        name: hello-world-rest-api  # container name
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service  # service maps to a pod but not deployment
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
  - nodePort: 31179
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
#    version: v1  # send requests only to v1 deployment
  sessionAffinity: None
  type: LoadBalancer
